@startuml 
title Prioritization of the Consumers (Mobile)
    actor "User" as user
    boundary "Directory Service" as dir
    create entity "Client Registry" as reg
    dir -> reg: create()
    collections "Dispatch Services" as dispatch
    boundary "Coaches iPads\n and Laptops" as coach
    coach -> "Dispatch Service" as dispatch: command(directoryService, register, priority)
    dispatch -> dir: command(register, client, priority)
    
    dispatch -> dir: fetchHandlers()
    dir --> dispatch: return(clientAddresses)
    
    coach -> dispatch: command(directoryService, subscribe, event)
    
    dispatch -> dir: command(subscribe, client, event)
    boundary "Tagging UI" as tag
    user -> tag: start()
    tag -> dispatch: command(streamingService, record)
    dispatch -> "Streaming Service" as strm: command(record)
    strm --> dispatch: notify(recordingStarts) 
    boundary "Mobile" as mobl
    strm -> mobl: startRecording()
    mobl -> mobl: Record()
    
    user -> tag: stop()

    tag -> dispatch: command(streamingService, save)
    dispatch -> strm: command(save)
    strm -> mobl: endRecording()
    mobl -> mobl: Stop()
    mobl --> strm: Notify(fileHandle)
    strm -> dir: fetchSubscribers(priority)
    dir --> strm: return(client, priority)
    create "File Transfer\nclient" as ft
    strm -> ft: create()
    strm -> ft: transferJob(fileHandle, client, priority)
    ft -> mobl: fetchVideo(fileHandle)
    mobl --> ft: return(mediaFile)
    loop for all subscribers
        ft --> dispatch: return(streamHandle)
    end

@enduml